from __future__ import annotations

from typing import Any, Generic, TypeVar

_RowT = TypeVar("_RowT")

class OperationalError(Exception): ...

class Cursor(Generic[_RowT]):
    def execute(self, query: object, params: object | None = None) -> Cursor[_RowT]: ...
    def executemany(self, query: object, params_seq: object) -> None: ...
    def fetchone(self) -> _RowT | None: ...
    def fetchall(self) -> list[_RowT]: ...
    def __enter__(self) -> Cursor[_RowT]: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...

class Connection(Generic[_RowT]):
    read_only: bool

    @classmethod
    def connect(cls, conninfo: str, *, row_factory: object | None = None) -> Connection[_RowT]: ...
    def execute(self, query: object, params: object | None = None) -> Cursor[_RowT]: ...
    def cursor(self) -> Cursor[_RowT]: ...
    def commit(self) -> None: ...
    def __enter__(self) -> Connection[_RowT]: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...

def __getattr__(name: str) -> Any: ...
