repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-format
        types_or: [python, pyi]
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args:
          - "-c"
          - "pyproject.toml"
          - "--severity-level"
          - "all"
          - "--confidence-level"
          - "all"
          - "-r"
          - "src"
          - "tests"
          - "scripts"
        additional_dependencies: ["bandit[toml]"]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=512"]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.(svg|patch)$
      - id: trailing-whitespace
        exclude: \.(svg|patch)$
