#!/bin/sh
set -eu

PROJECT_DIR=/opt/project-code-intelligence

: "${PROJECT_CODE_INTELLIGENCE_HF_MODEL_REPO:=Qwen/Qwen3-Embedding-0.6B-GGUF}"
: "${PROJECT_CODE_INTELLIGENCE_HF_MODEL_FILE:=Qwen3-Embedding-0.6B-Q8_0.gguf}"
: "${PROJECT_CODE_INTELLIGENCE_LLAMA_MODEL:=/models/$PROJECT_CODE_INTELLIGENCE_HF_MODEL_FILE}"
: "${PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER_N_GPU_LAYERS:=999}"
: "${PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER_PARALLEL:=4}"

mkdir -p /models

if [ -z "${PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER:-}" ]; then
	if [ -x /app/llama-server ]; then
		PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER=/app/llama-server
	else
		PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER=llama-server
	fi
fi

if [ ! -s "$PROJECT_CODE_INTELLIGENCE_LLAMA_MODEL" ]; then
	if [ -z "$PROJECT_CODE_INTELLIGENCE_HF_MODEL_REPO" ] || [ -z "$PROJECT_CODE_INTELLIGENCE_HF_MODEL_FILE" ]; then
		echo "Model not found and PROJECT_CODE_INTELLIGENCE_HF_MODEL_REPO/FILE are not set: $PROJECT_CODE_INTELLIGENCE_LLAMA_MODEL" >&2
		exit 1
	fi
	model_url="https://huggingface.co/$PROJECT_CODE_INTELLIGENCE_HF_MODEL_REPO/resolve/main/$PROJECT_CODE_INTELLIGENCE_HF_MODEL_FILE?download=true"
	echo "Downloading embedding model: $PROJECT_CODE_INTELLIGENCE_HF_MODEL_REPO/$PROJECT_CODE_INTELLIGENCE_HF_MODEL_FILE" >&2
	if [ -n "${HF_TOKEN:-}" ]; then
		curl -fL --retry 3 --retry-delay 2 -H "Authorization: Bearer $HF_TOKEN" -o "$PROJECT_CODE_INTELLIGENCE_LLAMA_MODEL" "$model_url"
	else
		curl -fL --retry 3 --retry-delay 2 -o "$PROJECT_CODE_INTELLIGENCE_LLAMA_MODEL" "$model_url"
	fi
fi

export PROJECT_CODE_INTELLIGENCE_LLAMA_MODEL
export PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER
export PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER_N_GPU_LAYERS
export PROJECT_CODE_INTELLIGENCE_LLAMA_SERVER_PARALLEL

exec "$PROJECT_DIR/pci-embedding-server"
